name: Check PR and README

on:
  pull_request:
    types: [labeled]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check labels
        id: check_labels
        uses: octokit/request-action@v2.1.0
        with:
          route: GET /repos/:owner/:repo/issues/:pull_number/labels
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check README changes
        id: check_readme
        uses: tj-actions/changed-files@v35.5.5
        with:
          files: README.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check main README changes
        id: check_main_readme
        run: |
          if [ -n "$(git diff --name-only origin/main HEAD | grep README.md)" ]; then echo "::set-output name=changed::true"; else echo "::set-output name=changed::false"; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.check_readme.outputs.any_changed == 'true' }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Step 1 passed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ contains(steps.check_labels.outputs.json, 'enhancement') && steps.check_main_readme.outputs.changed == 'true' }}
