name: Super-Linter

on:
  push:
    branches:
      - dev

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        with:
          auto_fix: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          LOG_LEVEL: debug
          VALIDATE_YAML: true
          AUTO_FIX: true
